$src="C:\Users\hajin\IT_Projects\hacking_study\dreamhack\811--3000-9\-3000.exe"   # <-- EDIT
if(!(Test-Path $src)){Write-Host "ERROR set src";exit}
$bodies=@'
{"P0": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "P1": "AAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAA", "P2": "AAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAA", "P3": "AAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAQQAA", "Q0": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "Q1": "AAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEA", "Q2": "AAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA@AAAAAAAAAAAAAAA", "Q3": "AAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA@AAAAAAAAAAAAAEA"}
'@ | ConvertFrom-Json
Remove-Item -Recurse -Force C:\a,C:\arun -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force C:\a | Out-Null
foreach($p in $bodies.PSObject.Properties){
  $tag=$p.Name;$full="C:\a\"+$p.Value+".exe"
  Copy-Item -LiteralPath $src -Destination $full -Force
  $o="C:\arun\"+$tag;New-Item -ItemType Directory -Force $o|Out-Null
  cmd /c "cd /d `"$o`" && `"$full`"" | Out-Null
  Write-Host ("##### "+$tag)
  Get-ChildItem -LiteralPath $o|Sort-Object CreationTime|ForEach-Object{
    $b=[System.IO.File]::ReadAllBytes($_.FullName)
    Write-Host (-join($b|ForEach-Object{$_.ToString("x2")}))
  }
}
Write-Host "##### DONE"
