AddHandler my-handler .dreamhack
LimitInternalRecursion 100
LoadModule module_4e6f34bdf4 my_modules/4e6f34bdf4.so
LoadModule module_d3c81e2853 my_modules/d3c81e2853.so
LoadModule module_ee09e4c325 my_modules/ee09e4c325.so
LoadModule module_9b713c9be5 my_modules/9b713c9be5.so
LoadModule module_7759dfd1f1 my_modules/7759dfd1f1.so
LoadModule module_0dfa4179fa my_modules/0dfa4179fa.so
