FROM ubuntu:24.04@sha256:c35e29c9450151419d9448b0fd75374fec4fff364a27f176fb458d472dfc9e54

RUN apt-get update && \
    apt-get install -y socat && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m ctf

WORKDIR /home/ctf

COPY korosensei .
COPY flag /flag

RUN chown root:ctf /flag && \
    chmod 440 /flag && \
    chown root:ctf /home/ctf/korosensei && \
    chmod 750 /home/ctf/korosensei

USER ctf

EXPOSE 1337

CMD ["socat", "TCP-LISTEN:1337,reuseaddr,fork", "EXEC:./korosensei"]